Port: 80
SiteTitle: 'Stupid Fucking News'
FeedURLs: 
- 'https://hnrss.org/frontpage'
- 'https://rss.orf.at/news.xml'
- 'https://www.heise.de/rss/heise.rdf'
- 'https://www.faz.net/rss/aktuell/'
Num_items: 15
